RENDER:
    out_dir: "test_renders"
    azimuth_angles: [0, 120, 240]
    elevation_angles: [0, 60, -60]
    trillis_asset: true
    replace_org_file: false
    fov_deg: 60
    resolution: [800, 600]
    mark: false

SEGMENTATION:
    device: "cuda"
    sam2_checkpoint: "./sam2/checkpoints/sam2_hiera_base_plus.pt"
    model_cfg: "../../sam2/sam2/configs/sam2/sam2_hiera_b+.yaml"
    points_per_side: 32
    points_per_batch: 128
    pred_iou_thresh: 0.7
    stability_score_thresh: 0.85
    stability_score_offset: 0.7
    crop_n_layers: 1
    box_nms_thresh: 0.7
    crop_n_points_downscale_factor: 1
    min_mask_region_area: 900
    use_m2m: false